//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.NewServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://grupp10/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pnr {
            get {
                return this.pnrField;
            }
            set {
                if ((object.ReferenceEquals(this.pnrField, value) != true)) {
                    this.pnrField = value;
                    this.RaisePropertyChanged("pnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://grupp10/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupp10/", ConfigurationName="NewServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://grupp10/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/HelloWorld", ReplyAction="*")]
        DataLayer.NewServiceReference.HelloWorldResponse HelloWorld(DataLayer.NewServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.HelloWorldResponse> HelloWorldAsync(DataLayer.NewServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://grupp10/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/GetContent", ReplyAction="*")]
        DataLayer.NewServiceReference.GetContentResponse GetContent(DataLayer.NewServiceReference.GetContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/GetContent", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetContentResponse> GetContentAsync(DataLayer.NewServiceReference.GetContentRequest request);
        
        // CODEGEN: Generating message contract since element name FindAllCustomersResult from namespace http://grupp10/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/FindAllCustomers", ReplyAction="*")]
        DataLayer.NewServiceReference.FindAllCustomersResponse FindAllCustomers(DataLayer.NewServiceReference.FindAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/FindAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.FindAllCustomersResponse> FindAllCustomersAsync(DataLayer.NewServiceReference.FindAllCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetCronusEmployeesResult from namespace http://grupp10/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/GetCronusEmployees", ReplyAction="*")]
        DataLayer.NewServiceReference.GetCronusEmployeesResponse GetCronusEmployees(DataLayer.NewServiceReference.GetCronusEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp10/GetCronusEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetCronusEmployeesResponse> GetCronusEmployeesAsync(DataLayer.NewServiceReference.GetCronusEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DataLayer.NewServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DataLayer.NewServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp10/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContent", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.GetContentRequestBody Body;
        
        public GetContentRequest() {
        }
        
        public GetContentRequest(DataLayer.NewServiceReference.GetContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp10/")]
    public partial class GetContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetContentRequestBody() {
        }
        
        public GetContentRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentResponse", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.GetContentResponseBody Body;
        
        public GetContentResponse() {
        }
        
        public GetContentResponse(DataLayer.NewServiceReference.GetContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp10/")]
    public partial class GetContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContentResult;
        
        public GetContentResponseBody() {
        }
        
        public GetContentResponseBody(string GetContentResult) {
            this.GetContentResult = GetContentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllCustomers", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.FindAllCustomersRequestBody Body;
        
        public FindAllCustomersRequest() {
        }
        
        public FindAllCustomersRequest(DataLayer.NewServiceReference.FindAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindAllCustomersRequestBody {
        
        public FindAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllCustomersResponse", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.FindAllCustomersResponseBody Body;
        
        public FindAllCustomersResponse() {
        }
        
        public FindAllCustomersResponse(DataLayer.NewServiceReference.FindAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp10/")]
    public partial class FindAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataLayer.NewServiceReference.Customer[] FindAllCustomersResult;
        
        public FindAllCustomersResponseBody() {
        }
        
        public FindAllCustomersResponseBody(DataLayer.NewServiceReference.Customer[] FindAllCustomersResult) {
            this.FindAllCustomersResult = FindAllCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCronusEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCronusEmployees", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.GetCronusEmployeesRequestBody Body;
        
        public GetCronusEmployeesRequest() {
        }
        
        public GetCronusEmployeesRequest(DataLayer.NewServiceReference.GetCronusEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCronusEmployeesRequestBody {
        
        public GetCronusEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCronusEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCronusEmployeesResponse", Namespace="http://grupp10/", Order=0)]
        public DataLayer.NewServiceReference.GetCronusEmployeesResponseBody Body;
        
        public GetCronusEmployeesResponse() {
        }
        
        public GetCronusEmployeesResponse(DataLayer.NewServiceReference.GetCronusEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp10/")]
    public partial class GetCronusEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataLayer.NewServiceReference.ArrayOfString[] GetCronusEmployeesResult;
        
        public GetCronusEmployeesResponseBody() {
        }
        
        public GetCronusEmployeesResponseBody(DataLayer.NewServiceReference.ArrayOfString[] GetCronusEmployeesResult) {
            this.GetCronusEmployeesResult = GetCronusEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : DataLayer.NewServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<DataLayer.NewServiceReference.WebServiceSoap>, DataLayer.NewServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.NewServiceReference.HelloWorldResponse DataLayer.NewServiceReference.WebServiceSoap.HelloWorld(DataLayer.NewServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DataLayer.NewServiceReference.HelloWorldRequest inValue = new DataLayer.NewServiceReference.HelloWorldRequest();
            inValue.Body = new DataLayer.NewServiceReference.HelloWorldRequestBody();
            DataLayer.NewServiceReference.HelloWorldResponse retVal = ((DataLayer.NewServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.HelloWorldResponse> DataLayer.NewServiceReference.WebServiceSoap.HelloWorldAsync(DataLayer.NewServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.NewServiceReference.HelloWorldResponse> HelloWorldAsync() {
            DataLayer.NewServiceReference.HelloWorldRequest inValue = new DataLayer.NewServiceReference.HelloWorldRequest();
            inValue.Body = new DataLayer.NewServiceReference.HelloWorldRequestBody();
            return ((DataLayer.NewServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.NewServiceReference.GetContentResponse DataLayer.NewServiceReference.WebServiceSoap.GetContent(DataLayer.NewServiceReference.GetContentRequest request) {
            return base.Channel.GetContent(request);
        }
        
        public string GetContent(string filename) {
            DataLayer.NewServiceReference.GetContentRequest inValue = new DataLayer.NewServiceReference.GetContentRequest();
            inValue.Body = new DataLayer.NewServiceReference.GetContentRequestBody();
            inValue.Body.filename = filename;
            DataLayer.NewServiceReference.GetContentResponse retVal = ((DataLayer.NewServiceReference.WebServiceSoap)(this)).GetContent(inValue);
            return retVal.Body.GetContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetContentResponse> DataLayer.NewServiceReference.WebServiceSoap.GetContentAsync(DataLayer.NewServiceReference.GetContentRequest request) {
            return base.Channel.GetContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetContentResponse> GetContentAsync(string filename) {
            DataLayer.NewServiceReference.GetContentRequest inValue = new DataLayer.NewServiceReference.GetContentRequest();
            inValue.Body = new DataLayer.NewServiceReference.GetContentRequestBody();
            inValue.Body.filename = filename;
            return ((DataLayer.NewServiceReference.WebServiceSoap)(this)).GetContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.NewServiceReference.FindAllCustomersResponse DataLayer.NewServiceReference.WebServiceSoap.FindAllCustomers(DataLayer.NewServiceReference.FindAllCustomersRequest request) {
            return base.Channel.FindAllCustomers(request);
        }
        
        public DataLayer.NewServiceReference.Customer[] FindAllCustomers() {
            DataLayer.NewServiceReference.FindAllCustomersRequest inValue = new DataLayer.NewServiceReference.FindAllCustomersRequest();
            inValue.Body = new DataLayer.NewServiceReference.FindAllCustomersRequestBody();
            DataLayer.NewServiceReference.FindAllCustomersResponse retVal = ((DataLayer.NewServiceReference.WebServiceSoap)(this)).FindAllCustomers(inValue);
            return retVal.Body.FindAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.FindAllCustomersResponse> DataLayer.NewServiceReference.WebServiceSoap.FindAllCustomersAsync(DataLayer.NewServiceReference.FindAllCustomersRequest request) {
            return base.Channel.FindAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.NewServiceReference.FindAllCustomersResponse> FindAllCustomersAsync() {
            DataLayer.NewServiceReference.FindAllCustomersRequest inValue = new DataLayer.NewServiceReference.FindAllCustomersRequest();
            inValue.Body = new DataLayer.NewServiceReference.FindAllCustomersRequestBody();
            return ((DataLayer.NewServiceReference.WebServiceSoap)(this)).FindAllCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.NewServiceReference.GetCronusEmployeesResponse DataLayer.NewServiceReference.WebServiceSoap.GetCronusEmployees(DataLayer.NewServiceReference.GetCronusEmployeesRequest request) {
            return base.Channel.GetCronusEmployees(request);
        }
        
        public DataLayer.NewServiceReference.ArrayOfString[] GetCronusEmployees() {
            DataLayer.NewServiceReference.GetCronusEmployeesRequest inValue = new DataLayer.NewServiceReference.GetCronusEmployeesRequest();
            inValue.Body = new DataLayer.NewServiceReference.GetCronusEmployeesRequestBody();
            DataLayer.NewServiceReference.GetCronusEmployeesResponse retVal = ((DataLayer.NewServiceReference.WebServiceSoap)(this)).GetCronusEmployees(inValue);
            return retVal.Body.GetCronusEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetCronusEmployeesResponse> DataLayer.NewServiceReference.WebServiceSoap.GetCronusEmployeesAsync(DataLayer.NewServiceReference.GetCronusEmployeesRequest request) {
            return base.Channel.GetCronusEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.NewServiceReference.GetCronusEmployeesResponse> GetCronusEmployeesAsync() {
            DataLayer.NewServiceReference.GetCronusEmployeesRequest inValue = new DataLayer.NewServiceReference.GetCronusEmployeesRequest();
            inValue.Body = new DataLayer.NewServiceReference.GetCronusEmployeesRequestBody();
            return ((DataLayer.NewServiceReference.WebServiceSoap)(this)).GetCronusEmployeesAsync(inValue);
        }
    }
}
